name: Test

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    strategy:
      matrix:
        node-version: ['22.18.0', '24.x']
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.13.1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          package-manager-cache: false
      - run: pnpm --version
      - run: pnpm install --frozen-lockfile
      - run: pnpm run typecheck
      - run: pnpm run build
      - run: pnpm test
      - name: Check lcov output
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == '22.18.0'
        shell: bash
        run: test -f ./coverage/lcov.info

      - name: Upload coverage to Coveralls
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == '22.18.0'
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.github_token }}
          file: ./coverage/lcov.info
